"""empty message

Revision ID: 214f839d0089
Revises: None
Create Date: 2014-07-19 17:31:42.365071

"""

# revision identifiers, used by Alembic.
revision = '214f839d0089'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
