"""empty message

Revision ID: 4cf2ccfc7c2f
Revises: 214f839d0089
Create Date: 2014-07-19 17:33:48.586200

"""

# revision identifiers, used by Alembic.
revision = '4cf2ccfc7c2f'
down_revision = '214f839d0089'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'level')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('level', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
